version: "3.9"

services:
  subnginx:
    image: "nginx:1.21.4"
    restart: always
    volumes:
      - ./nginx.conf/broker.conf:/etc/nginx/conf.d/broker.conf
    ports:
      - "9081:9081"
  
  pubnginx:
    image: "nginx:1.21.4"
    restart: always
    volumes:
      - ./nginx.conf/broker.conf:/etc/nginx/conf.d/broker.conf
    ports:
      - "9080:9080"

